# Generated by Django 4.1.3 on 2022-12-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
