# Generated by Django 4.1.3 on 2022-12-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_delete_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
    ]
